baseURL = "https://imsxx-blog.pages.dev/"  # 替换为 Cloudflare Pages 域名或自定义域名
     languageCode = "en-us"
     title = "My Hugo Site"
     theme = "github.com/imsxx/imsxx-blog"  # Go 模块主题路径
     [params]
       description = "A Hugo site with imsxx-blog theme"
