baseURL = "https://your-site-name.pages.dev/"
languageCode = "en-us"
title = "我的在线 Hugo 网站"
theme = "github.com/theNewDynamic/gohugo-theme-ananke" # 移除 @upgrade

[params]
  description = "一个完全在线部署的 Hugo 网站"
